"use client";

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from "./Providers";
import Navbar from '@/components/Navbar';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import {useRouter} from "next/navigation";
const inter = Inter({ subsets: ['latin'] })
import {Elements} from '@stripe/react-stripe-js';
import {loadStripe} from '@stripe/stripe-js';
import Hero from "@/components/Hero";
import Articles from "@/app/articles/page";
import Portfolio from "@/components/Portfolio";
import Brands from "@/components/Brands";
import Contact from "@/components/Contact";
import Team from "@/components/Team";
import Testimonials from "@/components/Testimonials";
import ScrollToTop from "@/components/ScrollToTop";
import Features from "@/components/Features";
import Admin from "@/app/admin/page";
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const stripePromise = loadStripe('pk_test_oKhSR5nslBRnBZpjO6KuzZeX');


export default function RootLayout({
  children,const: options = {
        // passing the client secret obtained from the server
        clientSecret: 'pk_test_oKhSR5nslBRnBZpjO6KuzZeX',
    }
}:{

  children: React.ReactNode
}) {



  return (
    <html lang="en">
        {/*
        <head /> will contain the components returned by the nearest parent
        head.js. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head ><title>Titovideo</title></head>
      <body className="dark:bg-black">
      <NextAuthProvider>
          <Elements stripe={stripePromise}>
           <Header />
              {children}
            </Elements>
          <ScrollToTop />
          <Footer/>
      </NextAuthProvider>
      </body>
    </html>
  )
}







